<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Train Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Continue to use TensorFlow Keras & a sample of the [Quickdraw dataset](https://github.com/googlecreativelab/quickdraw-dataset) to build a sketch classification model. The dataset has been sampled to only 10 classes and 10000 observations per class. Please build a baseline classification model then run a few experiments with different optimizers and learning rates. 

*Don't forgot to switch to GPU on Colab!*

### Write a function to load your data

Wrap yesterday's preprocessing steps into a function that returns four items:
* X_train
* y_train
* X_test
* y_test

Your function should accept a `path` to the data as a argument.

In [55]:
import numpy as np
import pandas as pd
import tensorflow as tf 
from sklearn.utils import shuffle
#data = np.load('../quickdraw10.npz')

In [38]:
len(data['arr_0'])

100000

In [46]:
temp = data['arr_0']
temp[0:10]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [53]:
from sklearn.model_selection import train_test_split

def load_quickdraw10(path):
    data = np.load('../quickdraw10.npz')
    X = data['arr_0']
    y = data['arr_1']
    
    X, y = shuffle(X, y)
    
    length = len(data['arr_0'])
    ratio = int(length * .8)
    
    X_train = X[0:ratio]
    y_train = y[0:ratio]
    X_test =  X[ratio:length]
    y_test = y[ratio:length]
    #print(len(X_train), len(y_train), len(X_test), len(y_test))
    #X_train, X_test, y_train, y_test = train_test_split(X, y test_size=0.20, random_state=42)
    return X_train, X_test, y_train, y_test

In [50]:
load_quickdraw10('../quickdraw10.npz')

80000 80000 20000 20000


(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 array([0, 0, 0, ..., 7, 7, 7], dtype=int64),
 array([8, 8, 8, ..., 9, 9, 9], dtype=int64))

### Write a Model Function
Using your model from yesterday, write a function called `create_model` which returns a compiled TensorFlow Keras Sequential Model suitable for classifying the QuickDraw-10 dataset. Include parameters for the following: 
* Learning Rate
* Optimizer

In [92]:
##### Your Code Here #####
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

def create_model(learning_rate=.0001, optimizer=tf.keras.optimizers.Adam()):
    model = Sequential()
    model.add(Dense(500, input_dim=784, activation='relu'))
    model.add(Dense(250, activation='relu'))
    model.add(Dense(125, activation='relu'))
    model.add(Dense(10, activation='softmax'))
    
    optimizer.learning_rate = learning_rate
    
    model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    return model

In [56]:
X_train, X_test, y_train, y_test = load_quickdraw10('../quickdraw10.npz')

In [93]:
model = create_model()

### Experiment with Batch Size
* Run 5 experiments with various batch sizes of your choice. 
* Visualize the results
* Write up an analysis of the experiments and select the "best" performing model among your experiments. Make sure to compare against your model's performance yesterday. 

In [94]:
results = model.fit(X_train, y_train, epochs=5)

Epoch 1/5
2500/2500 [==============================] - 4s 2ms/step - loss: 3.9469 - accuracy: 0.6453
Epoch 2/5
2500/2500 [==============================] - 4s 2ms/step - loss: 0.8574 - accuracy: 0.7583
Epoch 3/5
2500/2500 [==============================] - 4s 2ms/step - loss: 0.6146 - accuracy: 0.8149
Epoch 4/5
2500/2500 [==============================] - 4s 2ms/step - loss: 0.4909 - accuracy: 0.8478
Epoch 5/5
2500/2500 [==============================] - 4s 2ms/step - loss: 0.4057 - accuracy: 0.8723


### Experiment with Learning Rate
* Run 5 experiments with various learning rate magnitudes: 1, .1, .01, .001, .0001.
* Use the "best" batch size from the previous experiment
* Visualize the results
* Write up an analysis of the experiments and select the "best" performing model among your experiments. Make sure to compare against the previous experiments and your model's performance yesterday. 

In [95]:
create_model(learning_rate=.005).fit(X_train, y_train, epochs=5)

Epoch 1/5
2500/2500 [==============================] - 4s 2ms/step - loss: 5.3208 - accuracy: 0.2277
Epoch 2/5
2500/2500 [==============================] - 4s 2ms/step - loss: 1.3470 - accuracy: 0.5380
Epoch 3/5
2500/2500 [==============================] - 4s 2ms/step - loss: 1.1753 - accuracy: 0.5986
Epoch 4/5
2500/2500 [==============================] - 4s 2ms/step - loss: 1.1572 - accuracy: 0.6072
Epoch 5/5
2500/2500 [==============================] - 4s 2ms/step - loss: 1.1616 - accuracy: 0.6169


In [96]:
create_model(learning_rate=.0005).fit(X_train, y_train, epochs=5)

Epoch 1/5
2500/2500 [==============================] - 4s 2ms/step - loss: 1.2805 - accuracy: 0.7455
Epoch 2/5
2500/2500 [==============================] - 4s 2ms/step - loss: 0.5875 - accuracy: 0.8234
Epoch 3/5
2500/2500 [==============================] - 4s 2ms/step - loss: 0.4968 - accuracy: 0.8490
Epoch 4/5
2500/2500 [==============================] - 4s 2ms/step - loss: 0.4348 - accuracy: 0.8680
Epoch 5/5
2500/2500 [==============================] - 4s 2ms/step - loss: 0.3861 - accuracy: 0.8833


In [97]:
create_model(learning_rate=.00005).fit(X_train, y_train, epochs=5)

Epoch 1/5
2500/2500 [==============================] - 4s 2ms/step - loss: 3.1974 - accuracy: 0.6538
Epoch 2/5
2500/2500 [==============================] - 4s 2ms/step - loss: 1.0186 - accuracy: 0.7467
Epoch 3/5
2500/2500 [==============================] - 4s 2ms/step - loss: 0.7126 - accuracy: 0.7992
Epoch 4/5
2500/2500 [==============================] - 4s 2ms/step - loss: 0.5491 - accuracy: 0.8361
Epoch 5/5
2500/2500 [==============================] - 4s 2ms/step - loss: 0.4463 - accuracy: 0.8643


In [99]:
create_model(learning_rate=.000005).fit(X_train, y_train, epochs=10)

Epoch 1/10
2500/2500 [==============================] - 4s 2ms/step - loss: 13.4375 - accuracy: 0.4750
Epoch 2/10
2500/2500 [==============================] - 4s 2ms/step - loss: 6.5938 - accuracy: 0.6048
Epoch 3/10
2500/2500 [==============================] - 4s 2ms/step - loss: 4.8454 - accuracy: 0.6477
Epoch 4/10
2500/2500 [==============================] - 4s 2ms/step - loss: 3.8448 - accuracy: 0.6756
Epoch 5/10
2500/2500 [==============================] - 4s 2ms/step - loss: 3.1943 - accuracy: 0.6952
Epoch 6/10
2500/2500 [==============================] - 4s 2ms/step - loss: 2.7272 - accuracy: 0.7108
Epoch 7/10
2500/2500 [==============================] - 4s 2ms/step - loss: 2.3720 - accuracy: 0.7237
Epoch 8/10
2500/2500 [==============================] - 4s 2ms/step - loss: 2.0927 - accuracy: 0.7356
Epoch 9/10
2500/2500 [==============================] - 4s 2ms/step - loss: 1.8663 - accuracy: 0.7469
Epoch 10/10
2500/2500 [==============================] - 4s 2ms/step - loss: 1.67

In [101]:
create_model(learning_rate=.0000005).fit(X_train, y_train, epochs=50)

Epoch 1/50
2500/2500 [==============================] - 4s 2ms/step - loss: 49.5249 - accuracy: 0.1543
Epoch 2/50
2500/2500 [==============================] - 4s 2ms/step - loss: 29.2980 - accuracy: 0.2582
Epoch 3/50
2500/2500 [==============================] - 4s 2ms/step - loss: 22.8244 - accuracy: 0.3450
Epoch 4/50
2500/2500 [==============================] - 5s 2ms/step - loss: 19.0599 - accuracy: 0.4034
Epoch 5/50
2500/2500 [==============================] - 4s 2ms/step - loss: 16.5135 - accuracy: 0.4453
Epoch 6/50
2500/2500 [==============================] - 4s 2ms/step - loss: 14.6557 - accuracy: 0.4776
Epoch 7/50
2500/2500 [==============================] - 4s 2ms/step - loss: 13.2266 - accuracy: 0.5034
Epoch 8/50
2500/2500 [==============================] - 4s 2ms/step - loss: 12.0867 - accuracy: 0.5242
Epoch 9/50
2500/2500 [==============================] - 4s 2ms/step - loss: 11.1475 - accuracy: 0.5404
Epoch 10/50
2500/2500 [==============================] - 4s 2ms/step - lo

In [ ]:
# It would seem that the models performance increases the lower the learning rate, but you will need to train the model
# for substantially more training iterations to make up for the lower learning rate.
# Basically, there is a tradeoff between model performance and how many iterations the model must train for.

### Experiment with different Optimizers
* Run 5 experiments with various optimizers available in TensorFlow. See list [here](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers)
* Visualize the results
* Write up an analysis of the experiments and select the "best" performing model among your experiments. Make sure to compare against the previous experiments and your model's performance yesterday.
* Repeat the experiment combining Learning Rate and different optimizers. Does the best performing model change? 

In [104]:
create_model(learning_rate=.0005, optimizer=tf.keras.optimizers.SGD()).fit(X_train, y_train, epochs=5)

Epoch 1/5
2500/2500 [==============================] - 3s 1ms/step - loss: 1.8310 - accuracy: 0.6109
Epoch 2/5
2500/2500 [==============================] - 3s 1ms/step - loss: 0.8667 - accuracy: 0.7286
Epoch 3/5
2500/2500 [==============================] - 3s 1ms/step - loss: 0.7543 - accuracy: 0.7661
Epoch 4/5
2500/2500 [==============================] - 3s 1ms/step - loss: 0.6898 - accuracy: 0.7862
Epoch 5/5
2500/2500 [==============================] - 3s 1ms/step - loss: 0.6436 - accuracy: 0.7996


In [107]:
create_model(learning_rate=.0005, optimizer=tf.keras.optimizers.Adadelta()).fit(X_train, y_train, epochs=10)

Epoch 1/10
2500/2500 [==============================] - 4s 2ms/step - loss: 54.8442 - accuracy: 0.1392
Epoch 2/10
2500/2500 [==============================] - 4s 2ms/step - loss: 28.0409 - accuracy: 0.2449
Epoch 3/10
2500/2500 [==============================] - 4s 2ms/step - loss: 21.1659 - accuracy: 0.3365
Epoch 4/10
2500/2500 [==============================] - 4s 2ms/step - loss: 17.4899 - accuracy: 0.3930
Epoch 5/10
2500/2500 [==============================] - 5s 2ms/step - loss: 15.1058 - accuracy: 0.4340
Epoch 6/10
2500/2500 [==============================] - 4s 2ms/step - loss: 13.4236 - accuracy: 0.4627
Epoch 7/10
2500/2500 [==============================] - 5s 2ms/step - loss: 12.1537 - accuracy: 0.4853
Epoch 8/10
2500/2500 [==============================] - 5s 2ms/step - loss: 11.1524 - accuracy: 0.5034
Epoch 9/10
2500/2500 [==============================] - 5s 2ms/step - loss: 10.3412 - accuracy: 0.5196
Epoch 10/10
2500/2500 [==============================] - 4s 2ms/step - lo

In [108]:
create_model(learning_rate=.0005, optimizer=tf.keras.optimizers.Adamax()).fit(X_train, y_train, epochs=10)

Epoch 1/10
2500/2500 [==============================] - 4s 2ms/step - loss: 2.7904 - accuracy: 0.6735
Epoch 2/10
2500/2500 [==============================] - 4s 2ms/step - loss: 0.7107 - accuracy: 0.7914
Epoch 3/10
2500/2500 [==============================] - 4s 2ms/step - loss: 0.5315 - accuracy: 0.8390
Epoch 4/10
2500/2500 [==============================] - 4s 2ms/step - loss: 0.4358 - accuracy: 0.8658
Epoch 5/10
2500/2500 [==============================] - 4s 2ms/step - loss: 0.3682 - accuracy: 0.8862
Epoch 6/10
2500/2500 [==============================] - 4s 2ms/step - loss: 0.3128 - accuracy: 0.9035
Epoch 7/10
2500/2500 [==============================] - 4s 2ms/step - loss: 0.2673 - accuracy: 0.9172
Epoch 8/10
2500/2500 [==============================] - 4s 2ms/step - loss: 0.2264 - accuracy: 0.9302
Epoch 9/10
2500/2500 [==============================] - 4s 2ms/step - loss: 0.1920 - accuracy: 0.9411
Epoch 10/10
2500/2500 [==============================] - 4s 2ms/step - loss: 0.161

In [109]:
create_model(learning_rate=.0005, optimizer=tf.keras.optimizers.RMSprop()).fit(X_train, y_train, epochs=10)

Epoch 1/10
2500/2500 [==============================] - 7s 3ms/step - loss: 1.7465 - accuracy: 0.6848
Epoch 2/10
2500/2500 [==============================] - 8s 3ms/step - loss: 0.9450 - accuracy: 0.7573
Epoch 3/10
2500/2500 [==============================] - 7s 3ms/step - loss: 0.9166 - accuracy: 0.7699
Epoch 4/10
2500/2500 [==============================] - 7s 3ms/step - loss: 0.9767 - accuracy: 0.7609
Epoch 5/10
2500/2500 [==============================] - 7s 3ms/step - loss: 1.0627 - accuracy: 0.7469
Epoch 6/10
2500/2500 [==============================] - 7s 3ms/step - loss: 1.1481 - accuracy: 0.7284
Epoch 7/10
2500/2500 [==============================] - 8s 3ms/step - loss: 1.2157 - accuracy: 0.7051
Epoch 8/10
2500/2500 [==============================] - 9s 4ms/step - loss: 1.2930 - accuracy: 0.6661
Epoch 9/10
2500/2500 [==============================] - 8s 3ms/step - loss: 1.4114 - accuracy: 0.6497
Epoch 10/10
2500/2500 [==============================] - 8s 3ms/step - loss: 1.427

### Additional Written Tasks

1. Describe the process of backpropagation in your own words: 
```
It is a function that calculates that gradient of error for a function and attempts to find any local
minima / maxima of error for any given function. 
```



## Stretch Goals: 

- Implement GridSearch on anyone of the experiments
- On the learning rate experiments, implement [EarlyStopping](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/EarlyStopping)
- Review material on the math behind gradient descent: 

  - Gradient Descent
    - Gradient Descent, Step-by-Step  by StatQuest w/ Josh Starmer. This will help you understand the gradient descent based optimization that happens underneath the hood of neural networks. It uses a non-neural network example, which I believe is a gentler introduction. You will hear me refer to this technique as "vanilla" gradient descent. 
    - Stochastic Gradient Descent, Clearly Explained!!! by StatQuest w/ Josh Starmer. This builds on the techniques in the previous video.  This technique is the one that is actually implemented inside modern 'nets. 
These are great resources to help you understand tomorrow's material at a deeper level. I highly recommend watching these ahead of tomorrow.

  - Background Math
    - Dot products and duality by 3Blue1Brown. Explains the core linear algebra operation happening in today's perceptron.
The paradox of the derivative by 3Blue1Brown. Does a great job explaining a derivative. 
    - Visualizing the chain rule and product rule by 3Blue1Brown. Explains the black magic that happens within Stochastic Gradient Descent. 
These math resources are very much optional. They can be very heady, but I encourage you to explore. Your understanding of neural networks will greatly increase if you understand this math background.


